name: 'make a release or test build, sign it and publish to GH Releases'

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

env:
  is_release: ${{ startsWith(github.ref, 'refs/heads/release/') }}

defaults:
  run:
    working-directory: ./posanie

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make a release build
        if: ${{ env.is_release == 'true' }}
        run: ./gradlew --no-daemon assembleRelease

      - name: Make a beta build
        if: ${{ env.is_release == 'false' }}
        run: ./gradlew --no-daemon assembleBeta

      - name: Set up a path to APK build
        run: |
            if [ "$IS_RELEASE" = true ]; then
              echo "apk_path=./posanie/app/build/outputs/apk/release/" >> $GITHUB_ENV
            else
              echo "apk_path=./posanie/app/build/outputs/apk/beta/" >> $GITHUB_ENV
            fi
        env:
          IS_RELEASE: ${{ env.is_release }}

      - name: Sign a build
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          releaseDirectory: ${{ env.apk_path }}
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: posanie
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Patch version for beta-builds
        run: |
          echo -n $(cat version.txt | sed -e "s/.*/&/") >> ./version_patched
          echo -n "-$BRANCH_NAME-" >> ./version_patched
          echo -n $(date '+%m.%d.%Y-%H.%M.%S') >> ./version_patched
        if: ${{ env.is_release == 'false' }}
        env:
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Set version variable as a patched version
        run: |
            echo -n $(cat ./version_patched | sed -e "s/.*/version=&/") >> $GITHUB_ENV
        env:
          IS_RELEASE: ${{ env.is_release }}
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Release to GH Releases
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
          body_path: ./posanie/release_notes.txt
          tag_name: ${{ env.version }}
