name: build release app, sign it and publish to GH Releases

on:
  push:
    branch:
      # - "release/**'
      - "**"

defaults:
  run:
    working-directory: ./posanie

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build release
        run: ./gradlew --no-daemon assembleRelease
      - name: sign release build
        uses: r0adkll/sign-android-release@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          releaseDirectory: ./posanie/app/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: posanie
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          signedReleaseFile: ./posanie/app/build/outputs/apk/release/app-release.apk
      - name: create new release tag
        uses: amitsingh-007/next-release-tag@v2.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release to GH Releases
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ./app/build/outputs/apk/release/app-release.apk
          body_path: ./posanie/release_notes.txt
          tag_name: ${{ env.release_tag }}
